# Generated by Django 3.1.6 on 2021-02-12 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_created_post_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_image',
            new_name='image',
        ),
    ]
